name: ConvSym CI/CD

on:
  push:
    branches: [ "git-action" ]
  pull_request:
    branches: [ "git-action" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GCC and Make
      run: apt install g++ make
    - name: Compile ConvSym
      run: cd utils/convsym && ./build.sh
    - name: Test ConvSym
      run: cd utils/convsym && ./test.sh
 