name: ConvSym

on:
  push:
    branches: [ "master" ]
    paths: [ "utils/core/**", "utils/core-py/**", "utils/convsym/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "utils/core/**", "utils/core-py/**", "utils/convsym/**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd utils/convsym && make
    - name: Test
      run: cd utils/convsym && make test
 